version: '3'
services:
  webapp:
    build: ./
    volumes:       
      ## Used for production to store certs
      # - ./vault-autocert:/go/src/vault/vault-autocert
      ## Enable front end volume only for development
      - ./frontend:/go/src/vault/frontend
      # - E:/GoPaths/GoPath1/src/vault/vault-autocert:/go/src/vault/vault-autocert
      # - ~/dvolumes/vault/vault-autocert:/go/src/vault/vault-autocert
    ports:
      # Bind desired ports, recommended to use 80 and 443 for prod      
      - 8080:80
      - 6060:443
    environment:
      ## dev or prod
      - VAULT_MAC_ENV=dev
      ## white list domains for tls, comma seperated
      - VAULT_URLS=file.darrenyxj.com
    depends_on:
      - 'mongody'

  
  mongody:
    image: mongo:latest    
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    # volumes:
      ## Enable volumes to store data
      # - ./db-data/data/db:/data/db
      # - ~/dvolumes/vault/data/db:/data/db
    expose:
      - 27017
    ## Enable ports only for development purpose
    # ports:
    #   - 27017:27017

