version: '3'
services:
  webapp:
    build: ./
    volumes:       
      - ./vault-autocert:/go/src/vault/vault-autocert
      # - E:/GoPaths/GoPath1/src/vault/vault-autocert:/go/src/vault/vault-autocert
      # - ~/dvolumes/vault/vault-autocert:/go/src/vault/vault-autocert
    ports:
      - 8080:80
      - 6060:443
    environment:
      # dev or prod
      - VAULT_MAC_ENV=dev
    depends_on:
      - 'mongody'

  
  mongody:
    image: mongo:latest    
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db-data/data/db:/data/db
      # - ~/dvolumes/vault/data/db:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017

